### ISSUE TITLE
MW 1.32 - incompatible?

### ISSUE THREAD

**Issue by BluejacketScott** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#117]
Just installed on relatively fresh MW 1.32.0 and it doesn't show up.  Any chance I can provide more info to help troubleshoot?

**Comment by riparap** [comment]
Does console log of browser tell anything ..or php error log on server side?
I have not tested wysiwyg with MW1.32. Most like MediaWiki has been changed so that some deprecated things which wysiwyg is still using are not available anymore. If this is the case it can not be fixed by setup definitions, it will require modifications in code.

**Comment by BluejacketScott** [comment]
No, no errors in console or logs.  I am seeing a lot of 304 caches go by.  Is that perhaps interfering?

**Comment by JoeHorn** [comment]
I have the same issue.
It seems that ext.wysiwyg.*.js were not loaded.

**Comment by calebfergie** [comment]
Hi, I think I may be having an issue due to MW 1.32 compatibility. Here's a snippet of the log from PHP:

```
Original exception: [f15b92ee0589125bfd65e6b8] /index.php?title=Main_Page MWException from line 182 of /app/includes/MagicWord.php: Error: invalid magic word 'NORICHEDITOR'
Backtrace:
#0 /app/includes/MagicWordFactory.php(222): MagicWord->load(string)
#1 /app/includes/MagicWord.php(128): MagicWordFactory->get(string)
#2 /app/extensions/WYSIWYG-CKeditor/WYSIWYG/CKeditor.body.php(138): MagicWord::get(string)
#3 /app/includes/Hooks.php(174): CKeditor_MediaWiki::onParserBeforeInternalParse(Parser, string, StripState)
#4 /app/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
```

I know there's not yet 1.32 support for this extension but I think this error may be due to this change from the [release notes](https://www.mediawiki.org/wiki/Release_notes/1.32):

```
- All MagicWord static member variables have been removed. Use appropriate hooks or MagicWordFactory methods instead.
```

Just wondering if there are any quick fixes to try?

Here's the [GH for my project](https://github.com/calebfergie/mediawiki/), deployed [here](https://ncp-wiki.herokuapp.com/).

Thanks for any feedback :)

**Comment by Shaker1978** [comment]
Same thing here. Followed the simple install instructions - unzip into extensions, put wfLoadExtension( 'WYSIWYG' ); into LocalSettings, and I have a lot of options now in the user settings regarding the "Texteditor", but it doesn't come up on editing. Which MW version is the latest one supported?

**Comment by Shaker1978** [comment]
Same thing here. Followed the simple install instructions - unzip into extensions, put wfLoadExtension( 'WYSIWYG' ); into LocalSettings, and I have a lot of options now in the user settings regarding the "Texteditor", but it doesn't come up on editing. Which MW version is the latest one supported? 1.31 because it's the latest one listed in the table?

**Comment by stopspazzing** [comment]
> Original exception: [f15b92ee0589125bfd65e6b8] /index.php?title=Main_Page MWException from line 182 of /app/includes/MagicWord.php: Error: invalid magic word 'NORICHEDITOR'
> Backtrace:
> 0 /app/includes/MagicWordFactory.php(222): MagicWord->load(string)
> 1 /app/includes/MagicWord.php(128): MagicWordFactory->get(string)
> 2 /app/extensions/WYSIWYG-CKeditor/WYSIWYG/CKeditor.body.php(138): MagicWord::get(string)
> 3 /app/includes/Hooks.php(174): CKeditor_MediaWiki::onParserBeforeInternalParse(Parser, string, StripState)
> 4 /app/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)


Comment out line 138 & 344 in CKeditor.body.php
What other errors are displayed after you do this?

**Comment by Yannick86** [comment]
Anyone any news about this? I'm having the exact same issue ... :(
Stopsspazzing, I have tried what you suggested, however still nothing is being shown.

**Comment by calebfergie** [comment]
@Yannick86 I haven't tried what @stopspazzing suggested - ended up using a different extension. However, if you follow their instructions, do you get any errors?

**Comment by Yannick86** [comment]
I don't get anything :( .. where exactly do you see those errors?

**Comment by Yannick86** [comment]
& yes, I noticed on your website that you used Tiny wysiwyg.
This one does work, but it bugs with the dynamiclist extension.

**Comment by calebfergie** [comment]
@Yannick86 I'm not a mediawiki pro by any means so I'm not sure if you'll find it helpful but... for my setup, I would get helpful error information both from:

1. The browser page, after setting the following in my `LocalSettings.php` file: ```$wgShowExceptionDetails = true;```
2. The console/log of the server running the mediawiki (in my case this was heroku's log).

**Comment by usbport11** [comment]
Left possible solution in another thread: https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor/issues/122
Looks like it work.

**Comment by Yannick86** [comment]
This does indeed fix the issue. Thanks a bunch!

Sad news for me is that none of the WYSIWYG editors are able to work with the 
https://www.mediawiki.org/wiki/Extension:DynamicPageList3
&
https://www.mediawiki.org/wiki/Extension:ClipUpload
extensions

I will start a new thread for this.

**Comment by usbport11** [comment]
Thanks for feedback. Maybe official developers fix these issues in right way.
