### ISSUE TITLE
MW 1.33 - incompatible

### ISSUE THREAD

**Issue by lancemitchell** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#125]
Tried to install https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor.git into MW 1.33 installation with many resulting issues.

- MW 1.33  comes with WikiEditor 0.5.2, which is higher than bundled 0.5.1, resulting in error 
PHP Fatal error:  Uncaught ExtensionDependencyError: CodeEditor is not compatible with the current installed version of WikiEditor (0.5.1), it requires: >= 0.5.2.

- Loading page reports the following error after adding "wfLoadExtension( 'WYSIWYG' );" and "wfLoadExtension( 'WikiEditor' );" to LocalSettings.php

PHP Deprecated:  Use of EditPage::getContextTitle called with no title set was deprecated in MediaWiki 1.32. [Called from CodeEditorHooks::editPageShowEditFormInitial in /<WIKIPATH>/extensions/CodeEditor/includes/CodeEditorHooks.php at line 48] in /<WIKIPATH>/includes/debug/MWDebug.php on line 309

[21-Sep-2019 03:44:42 UTC] PHP Deprecated:  Use of MagicWord::get was deprecated in MediaWiki 1.32. [Called from CKeditor_MediaWiki::onParserBeforeInternalParse in /<WIKIPATH>/extensions/WYSIWYG-src/WYSIWYG/CKeditor.body.php at line 138] in /<WIKIPATH>/includes/debug/MWDebug.php on line 309

[21-Sep-2019 03:44:42 UTC] PHP Notice:  "" is not a valid magic word for "NORICHEDITOR" [Called from Language::getMagic in /<WIKIPATH>/languages/Language.php at line 3220] in /<WIKIPATH>/includes/debug/MWDebug.php on line 309

**Comment by usbport11** [comment]
Make clear installation mediawiki 1.33.0 (VM CentOS 7):
MediaWiki | 1.33.0
PHP | 7.2.22 (apache2handler)
MariaDB | 5.5.64-MariaDB

Then follow https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor/issues/122. 
All works good. 

Update:
Get last WikiEditor and get same thing.
Rotate to previous WiKiEditor vesrion

**Comment by usbport11** [comment]
Prepare system (OS, packages, db, files, etc)
Download stanble mediawiki version
https://releases.wikimedia.org/mediawiki/1.33/mediawiki-1.33.1.tar.gz
Make web install
Remove standard version of WikiEditor
Download latest WikiEditor, copy to extensions
https://github.com/wikimedia/mediawiki-extensions-WikiEditor (mediawiki-extensions-WikiEditor-master.zip)

Add extension in LocalSettings.php
wfLoadExtension( 'WikiEditor' );
Result:
Error 500

Enable reporting in LocalSettings.php
error_reporting( -1 );
ini_set( 'display_errors', 1 );
Result:
Fatal error: Uncaught ExtensionDependencyError: WikiEditor is not compatible with the current MediaWiki core (version 1.33.1), 
it requires: >= 1.34.0. in /var/www/html/mediawiki/includes/registration/ExtensionRegistry.php:323 
Stack trace: 
#0 /var/www/html/mediawiki/includes/registration/ExtensionRegistry.php(172): ExtensionRegistry->readFromQueue(Array) 
#1 /var/www/html/mediawiki/includes/Setup.php(127): ExtensionRegistry->loadFromQueue() 
#2 /var/www/html/mediawiki/includes/WebStart.php(77): require_once('/var/www/html/m...') 
#3 /var/www/html/mediawiki/index.php(39): require('/var/www/html/m...') 
#4 {main} thrown in /var/www/html/mediawiki/includes/registration/ExtensionRegistry.php on line 323

Trying lower version of mediawiki
extension.json
"requires": {
		"MediaWiki": ">= 1.33.0"
	},
Result
No errors, but and no wikieditor

Delete wikieditor
Download version for 1.33.0 
https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/WikiEditor/+archive/REL1_33.tar.gz

Copy extension
Result:
All good

**Comment by kenmont** [comment]
WYSIWYG Editor not working on CentOS7 with MediaWiki 1.34. php 7.3 MySQL 5.7.3 
I Followed https://www.mediawiki.org/wiki/Extension:WYSIWYG and get a blank page
the page saves that 1.3.1 Branch wysiwyg_mv130_462 contains latest modifications, version 1.5.6_0 [B551+18.09.2018] and php 7.2  

I did the follwoing:
Download WYSIWYG #6 bundle in your <wiki installation directory>/extensions/WYSIWYG-src directory and publish its sub-directories as wiki extensions, still keeping the original WikiEditor extension (if any). For example:
cd wiki/extensions/
git clone https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor.git WYSIWYG-src
ln -s WYSIWYG-src/WYSIWYG  WYSIWYG
ln -s WYSIWYG-src/SemanticForms SemanticForms
mv WikiEditor WikiEditor-org
ln -s WYSIWYG-src/WikiEditor WikiEditor

I got a blank screen, but got an exception on the main page.
when I Set $wgShowExceptionDetails = true; in LocalSettings the server crashes (http response 500).

I tried https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor/issues/125 process, but stil crashes the server if I  try to set exception details.

**Comment by usbport11** [comment]
Hi.
First, make sure that wikieditor work (disable WYSIWYG and get wikieditor version compatible with your wiki version).
Second, try steps from [here](https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor/issues/122).

**Comment by kenmont** [comment]
thanks usbport11,
I downloaded this version mediawiki
https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.0.tar.gz
then I removed the WikiEditor and SemanticForms from extensions mediawiki/extensions
copied the 1.3.4  WikiEditor to mediawiki/extensions
commented out in LocalSettings
wfLoadExtension( 'WYSIWYG' );
$wgShowExceptionDetails

When to go my site:
my main page shows I have to login and this is displayed on the main page:
[XhDvrfWMXAXCe7cEEQ3t4AAAANY] 2020-01-04 20:03:57: Fatal exception of type "MWException"
also I saw {sitename} instead of my site. This only happen the first time I did the changes.

I then did the following:
I login and the main page redirects to my home page with internal wiki links (as expected).
I log out and login again as admin. I go to special pages and version

WikiEditor
0.5.2
GPL-2.0-or-later
Provides an advanced, extensible wikitext editing interface
Derk-Jan Hartman, Trevor Parscal, Roan Kattouw, Nimish Gautam and Adam Miller

Shows WikiEditor is installed.
I then edit a page and the editor works as expected without WYSIWYG.

Can you please confirm the link for WYSIWYG version I should use?

**Comment by usbport11** [comment]
Hi again!
Another thing how i can try to help you - list all steps that i do for success.

1) download centos 7 (in my case CentOS-7-x86_64-Minimal-1810.iso)
2) install
3) vi /etc/selinux/config
SELINUX=disabled
4) reboot
5) systemctl stop NetworkManager
6) systemctl disable NetworkManager
7) vi /etc/sysconfig/network-scripts/ifcfg-enp0s3
ONBOOT=yes
DEFROUTE=yes
BOOTPROTO=static
IPADDR=192.168.1.12
NETMASK=255.255.255.0
NETWORK=192.168.1.0
GATEWAY=192.168.1.1
8) vi /etc/resolv.conf
nameserver 192.168.1.1
9) systemctl restart network
10) ping 8.8.8.8
OK
11) ping google.com
OK
12) yum update
13) yum install wget nano net-tools yum-utils unzip
14) cd /tmp
15) wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
16) wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm
17) yum install epel-release-latest-7.noarch.rpm
18) yum install remi-release-7.rpm
17) yum-config-manager --enable remi-php73
18) yum install httpd mariadb mariadb-server php php-mysql php-xml php-mbstring
19) systemctl start mariadb
20) mysql_secure_installation
root
toor
21) mysql -u root -p
22) create database wikidb;
23) show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| wikidb             |
+--------------------+
24) quit
25) wget https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.0.tar.gz
26) tar -C /var/www/html/ -xvf mediawiki-1.34.0.tar.gz
27) mv /var/www/html/mediawiki-1.34.0 /var/www/html/mediawiki
28) systemctl start httpd
29) systemctl stop firewalld
30) open in browser http://192.168.1.12/mediawiki/ and make install
host - localhost
db name - wikidb
db username - root
db password - toor
wiki title - testwiki
admin username - admin
admin password - somepassword
that's enough
31) copy LocalSettings.php in mediawiki folder
32) enter your wiki, check that it work and create new article
33) view version
MediaWiki	1.34.0
PHP			7.3.13 (apache2handler)
MariaDB		5.5.64-MariaDB
34) mv /var/www/html/mediawiki/extensions/WikiEditor /var/www/html/mediawiki/extensions/_WikiEditor
35) mkdir /var/www/html/mediawiki/extensions/WikiEditor
36) wget https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/WikiEditor/+archive/REL1_34.tar.gz
37) tar -C /var/www/html/mediawiki/extensions/WikiEditor -xvf REL1_34.tar.gz
38) nano /var/www/html/mediawiki/LocalSettings.php
wfLoadExtension('WikiEditor');
39) check that editor work (in my case i am need to clear browser cache - editor not show at first time)
40) wget https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor/archive/wysiwyg_mw130_462.zip
41) mkdir /var/www/html/mediawiki/extensions/WYSIWYG
42) unzip wysiwyg_mw130_462.zip -d /tmp/WYSIWYG-CKeditor-wysiwyg_mw130_462/WYSIWYG
43) cp -R /tmp/WYSIWYG-CKeditor-wysiwyg_mw130_462/WYSIWYG /var/www/html/mediawiki/extensions/
44) cd /var/www/html/mediawiki/extensions/WYSIWYG
45) rm -fr ckeditor_source
46) rm -fr tests_selenium
47) rm -fr tests_selenium_ext_img
48) nano extension.json
remove:
"LanguageGetMagic"              : ["CKeditor_MediaWiki::onLanguageGetMagic"],
"LanguageGetMagic"              : ["CKeditor_MediaWiki::onLanguageGetMagic"],
49) nano CKeditor.body.php
rem strings:

//public static function onLanguageGetMagic( &$magicWords, $langCode ) {
//$magicWords['NORICHEDITOR'] = array( 0, 'NORICHEDITOR' );
//return true;
//}

//MagicWord::get( 'NORICHEDITOR' )->matchAndRemove( $text );

//MagicWord::get( 'NORICHEDITOR' )->matchAndRemove( $text );

50) nano CKeditorEditPage.body.php
change
function getPreviewText() {
	if( !$this->isCssJsSubpage ) {
		wfRunHooks( 'EditPageBeforePreviewText', array( &$this, $this->previewOnOpen() ) );
		$result = parent::getPreviewText();
		wfRunHooks( 'EditPagePreviewTextEnd', array( &$this, $this->previewOnOpen() ) );
	} else {
		$result = parent::getPreviewText();
	}
       return $result;
}
to
function getPreviewText() {
	$result = parent::getPreviewText();
	return $result;
}
51) nano /var/www/html/mediawiki/LocalSettings.php
$wgGroupPermissions['*']['wysiwyg']=true;
$wgGroupPermissions['user']['wysiwyg']=true;
$wgDefaultUserOptions['riched_disable'] = false;
$wgDefaultUserOptions['riched_start_disabled'] = false;
$wgDefaultUserOptions['riched_use_toggle'] = true;
$wgDefaultUserOptions['riched_use_popup'] = false;
$wgDefaultUserOptions['riched_toggle_remember_state'] = true;
$wgDefaultUserOptions['riched_link_paste_text'] = true;
$wgDefaultUserOptions['showtoolbar'] = true;
wfLoadExtension('WYSIWYG');
wfLoadExtension('WikiEditor');

52) Checking
OK

**Comment by kenmont** [comment]
thanks  again usbport11,
I followed from step 38 as I had WikiEditor setup properly from you previous post.  I confirm that WYSIWYG is working properly now. Your last post will help put this issue for new MediaWiki 1.3.4 installs

**Comment by iancrossfield** [comment]
Note that Line 40 (in @usbport11 's  instructions above) should have a semicolon after it.  Otherwise, it all worked for me on MW 1.35.

**Comment by usbport11** [comment]
> Note that Line 40 (in @usbport11 's instructions above) should have a semicolon after it. Otherwise, it all worked for me on MW 1.35.

Thank you. Fixed.
